[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_program = "FV451y9S6Pe6qNFbBrdyJkdAY6mcsEex6Mjf49aKjuY2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
